import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Engine} from '../lib/engine.mjs';
import {createStudio} from '../server.mjs';
import {verifyBrowserEvidence} from '../lib/browser-bridge.mjs';
import {saveMedia,getMedia} from '../lib/media.mjs';
import {localOrigin,allowedURL} from '../extension/protocol.js';
const extensionId='a'.repeat(32),date='2026-09-22T00:00:00Z';
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'relay-browser-'));let now=new Date(date);const e=await new Engine({dataDir:dir,credentials:{},now:()=>now}).init();t.after(async()=>{await e.close();await rm(dir,{recursive:true,force:true});});await e.browser.pair({extensionId});await e.browser.heartbeat({version:'0.2.0'});await e.browser.connect({platform:'x',accountId:'tester',observedAccountId:'tester',verified:true});return {e,dir,setNow:v=>now=new Date(v)};}
async function queued(e){const d=await e.save({selected:['x'],common:{body:'test body'},overrides:{}});return (await e.enqueue(d.id,d.revision,true))[0];}
const evidence=()=>({accountId:'tester',body:'test body',title:'',permalink:'https://x.com/tester/status/123',publishedAt:date});
test('browser work is isolated from API worker; concurrent claims and final authorization happen once',async t=>{const {e}=await fixture(t);await queued(e);await e.tick();assert.equal(e.state.jobs[0].status,'queued');const results=await Promise.all([e.browser.claim(),e.browser.claim()]);assert.equal(results.filter(Boolean).length,1);const j=results.find(Boolean),arm={jobId:j.id,lease:j.lease,accountId:j.accountId,contentHash:j.contentHash};await assert.rejects(e.browser.arm({...arm,accountId:'someone_else'}));await assert.rejects(e.browser.arm({...arm,contentHash:'changed'}));await e.browser.arm(arm);await assert.rejects(e.browser.arm(arm));await e.browser.result({jobId:j.id,lease:j.lease,outcome:'published',evidence:evidence()});assert.equal(e.state.jobs[0].status,'published');assert.equal(await e.browser.claim(),null);});
test('a failed operation after final authorization is unknown, never retried',async t=>{const {e}=await fixture(t);await queued(e);const j=await e.browser.claim();await e.browser.arm({jobId:j.id,lease:j.lease,accountId:j.accountId,contentHash:j.contentHash});await e.browser.result({jobId:j.id,lease:j.lease,outcome:'failed',error:'disconnect'});assert.equal(e.state.jobs[0].status,'unknown');assert.equal(await e.browser.claim(),null);await assert.rejects(e.reconcile(j.id));});
test('expired lease cannot click or report success; no automatic replay',async t=>{const {e,setNow}=await fixture(t);await queued(e);const j=await e.browser.claim();setNow('2026-09-22T00:05:00Z');await e.browser.heartbeat({version:'0.2.0'});assert.equal(e.state.jobs[0].status,'unknown');await assert.rejects(e.browser.arm({jobId:j.id,lease:j.lease,accountId:j.accountId,contentHash:j.contentHash}));assert.equal(await e.browser.claim(),null);});
test('account mismatch, disconnected extension and pause block registration or final click',async t=>{const {e,setNow}=await fixture(t);await assert.rejects(e.browser.connect({platform:'note',accountId:'expected',observedAccountId:'other',verified:true}));const j=await queued(e);await e.settings({...e.state.settings,paused:true});assert.equal(await e.browser.claim(),null);await e.settings({...e.state.settings,paused:false});const claimed=await e.browser.claim();await e.settings({...e.state.settings,paused:true});await assert.rejects(e.browser.arm({jobId:j.id,lease:claimed.lease,accountId:'tester',contentHash:claimed.contentHash}));setNow('2026-09-22T00:02:00Z');const d=await e.save({selected:['x'],common:{body:'new'},overrides:{}});await assert.rejects(e.enqueue(d.id,d.revision,true),/Chrome/);});
test('evidence requires exact account, complete body, owned URL and real time',()=>{const j={platform:'x',accountId:'tester',content:{body:'test body'},attemptAt:date};const now=new Date(date);assert.equal(verifyBrowserEvidence(j,evidence(),now).remoteId,'123');for(const bad of [{accountId:'other'},{body:'test'},{permalink:'https://x.com.evil.test/tester/status/123'},{permalink:'https://x.com/other/status/123'},{publishedAt:'2026-09-20T00:00:00Z'},{publishedAt:'2026-09-23T00:00:00Z'},{permalink:'bad'}])assert.throws(()=>verifyBrowserEvidence(j,{...evidence(),...bad},now));});
test('browser feedback respects actual 48h, missing values and interrupted collection',async t=>{const {e,setNow}=await fixture(t);const j=await queued(e);Object.assign(j,{status:'published',publishedAt:date,permalink:'https://x.com/tester/status/123',remoteId:'123'});setNow('2026-09-23T23:59:59Z');assert.equal(await e.browser.feedbackWork(),null);setNow('2026-09-24T00:00:00Z');const f=await e.browser.feedbackWork();assert.equal(await e.browser.feedbackWork(),null);await e.browser.feedbackResult({jobId:j.id,lease:f.feedbackLease,evidence:{accountId:'tester',permalink:j.permalink},metrics:{likes:0}});assert.equal(j.observations[0].metrics.likes,0);assert.equal(j.observations[0].metrics.views,undefined);assert.equal(j.observations[0].period,'publication_48h');delete j.feedbackAttempt;const second=await e.browser.feedbackWork();setNow('2026-09-24T00:05:00Z');await e.browser.heartbeat({version:'0.2.0'});assert.equal(j.feedbackAttempt,'unavailable');await assert.rejects(e.browser.feedbackResult({jobId:j.id,lease:second.feedbackLease,metrics:{likes:1}}));});
test('stored images use opaque local IDs, reject executable and missing content',async t=>{const {dir,e}=await fixture(t);const png=Buffer.from('89504e470d0a1a0a','hex');const m=await saveMedia(dir,{base64:png.toString('base64')});assert.equal((await getMedia(dir,m.id)).type,'image/png');await assert.rejects(saveMedia(dir,{base64:Buffer.from('<svg onload="bad">').toString('base64')}));await assert.rejects(getMedia(dir,'../../secret'));const d=await e.save({selected:['x'],common:{body:'test',attachmentId:'00000000-0000-4000-8000-000000000000'},overrides:{}});await assert.rejects(e.enqueue(d.id,d.revision,true));assert.equal(e.state.jobs.length,0);});
test('extension permission boundary rejects lookalikes, other ports and unrelated sites',async()=>{assert.ok(localOrigin('http://127.0.0.1:8792/#settings'));assert.ok(!localOrigin('http://127.0.0.1:8791/'));assert.ok(!localOrigin('https://127.0.0.1:8792/'));assert.ok(allowedURL('note','https://editor.note.com/notes/new'));for(const u of ['https://x.com.evil.test/','https://x.com:8443/','http://x.com/','https://name:secret@x.com/'])assert.ok(!allowedURL('x',u));const m=JSON.parse(await readFile(new URL('../extension/manifest.json',import.meta.url)));assert.ok(!m.permissions.includes('cookies'));assert.ok(!m.host_permissions.includes('<all_urls>'));});
test('HTTP bridge requires BOTH paired extension and current CSRF, and denies extension state reads',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'relay-bridge-http-'));const a=await createStudio({dataDir:dir,credentials:{},worker:false});await new Promise(r=>a.server.listen(0,'127.0.0.1',r));t.after(async()=>{await a.close();await rm(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${a.server.address().port}`,state=await (await fetch(base+'/api/state')).json();const post=(route,body,headers={})=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':state.csrf,...headers},body:JSON.stringify(body)});await post('/api/bridge/pair',{extensionId});const headers={Origin:'chrome-extension://'+extensionId,'X-Relay-Extension':extensionId};assert.equal((await post('/api/bridge/heartbeat',{version:'0.2.0'},headers)).status,200);assert.equal((await post('/api/bridge/heartbeat',{version:'0.2.0'},{...headers,'X-Studio-Token':'bad'})).status,403);assert.equal((await post('/api/bridge/heartbeat',{version:'0.2.0'},{...headers,Origin:'https://evil.test'})).status,403);assert.equal((await post('/api/bridge/heartbeat',{version:'0.2.0'})).status,403);assert.equal((await fetch(base+'/api/state',{headers})).status,403);});

test('disconnected browser jobs expire without a claim, and cannot silently remain queued',async t=>{const {e,setNow}=await fixture(t);await queued(e);setNow('2026-09-22T00:16:00Z');await e.tick();assert.equal(e.state.jobs[0].status,'failed');});
test('an explicit current observation before 48h does not consume the automatic 48h observation',async t=>{const {e,setNow}=await fixture(t);const j=await queued(e);Object.assign(j,{status:'published',publishedAt:date,permalink:'https://x.com/tester/status/123',remoteId:'123'});await e.collectNow(j.id);const work=await e.browser.feedbackWork();await e.browser.feedbackResult({jobId:j.id,lease:work.feedbackLease,evidence:{accountId:'tester',permalink:j.permalink},metrics:{likes:0}});assert.equal(j.observations[0].period,'current_lifetime');assert.equal(j.feedbackAttempt,undefined);setNow('2026-09-24T00:00:00Z');assert.equal((await e.browser.feedbackWork()).id,j.id);});

test('server restart preserves interrupted browser jobs as unknown and does not resend',async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'relay-restart-'));let e=await new Engine({dataDir:dir,credentials:{}}).init();
 t.after(async()=>{await e.close();await rm(dir,{recursive:true,force:true});});
 e.state.jobs.push({id:'interrupted',platform:'x',transport:'browser',status:'sending',phase:'final-click',lease:'old',content:{body:'test'},observations:[]});await e.persist();await e.close();
 e=await new Engine({dataDir:dir,credentials:{}}).init();assert.equal(e.state.jobs[0].status,'unknown');assert.equal(await e.browser.claim(),null);await e.tick();assert.equal(e.state.jobs[0].status,'unknown');
});
